version: '3.3'

# Use root/example as user/password credentials
services:
  db:
    container_name: akd-test-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "8001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: default
    healthcheck:
      test: ["CMD", "mysqladmin", "-P", "8001", "--password=example", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
